### ISSUE TITLE
Site/Docs page gives stack trace

### ISSUE THREAD

**Issue by staypufd** [juxt/yada#108]
Going to https://juxt.pro/yada gives stack trace.

404: Not Found

The requested resource could not be found but may be available again in the future.

clojure.lang.ExceptionInfo:  {:status 404}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at yada.resource$eval30592$fn__30593$fn__30594.invoke(resource.clj:113)
	at manifold.deferred$eval14998$chain___15019.invoke(deferred.clj:860)
	at manifold.deferred$chain.invoke(deferred.clj:929)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:632)
	at yada.handler$handle_request_with_maybe_subresources.invoke(handler.clj:121)
	at yada.handler$handle_request.invoke(handler.clj:169)
	at yada.handler.Handler.request(handler.clj:224)
	at bidi.vhosts$make_handler$fn__4623.invoke(vhosts.clj:160)
	at aleph.http.server$handle_request$fn__25185$f__14319__auto____25186.invoke(server.clj:154)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__14201$f__14202.invoke(executor.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)

**Comment by malcolmsparks** [comment]
Thanks. There was no redirect for yada -> yada/index.html - that's been fixed now.
