### ISSUE TITLE
Setting `Accept-Charset` header leads to an exception

### ISSUE THREAD

**Issue by mishok13** [juxt/yada#126]
When trying to access `yada` powered service with the following resource (edited for brevity):

```clojure
(yada/resource {:id :com.autheos.event.resources/event
                  :methods
                  {:get
                   {:produces #{"application/json;q=0.9"
                                "application/edn;q=0.1"}
                    :consumes #{"*/*"}
                    :response (fn [ctx] "")}}})
```

produces the following when `Accept-Charset` header is passed:

```
$ curl -gv 'localhost:5000/event' -H 'Accept-Charset: *'                                                                                                                                          
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /event HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.47.0
> Accept: */*
> Accept-Charset: *
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain
< Server: Aleph/0.4.1
< Connection: Keep-Alive
< Date: Fri, 07 Oct 2016 11:52:10 GMT
< content-length: 1165
< 
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class java.lang.NullPointerException: java.lang.NullPointerException
        at cheshire.generate$generate.invoke(generate.clj:154)
        at cheshire.generate$generate.invoke(generate.clj:124)
        at cheshire.core$generate_string.invoke(core.clj:73)
        at yada.body$eval20657$fn__20658.invoke(body.clj:166)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at yada.body$eval20637$fn__20638.invoke(body.clj:89)
        at yada.body$eval20501$fn__20502$G__20490__20509.invoke(body.clj:34)
        at yada.handler$standard_error.invoke(handler.clj:73)
        at yada.handler$handle_request_with_maybe_subresources$fn__24625.invoke(handler.clj:150)
        at manifold.deferred$catch_SINGLEQUOTE_$fn__7283.invoke(deferred.clj:964)
        at manifold.deferred.Listener.onError(deferred.clj:220)
        at manifold.deferred.Deferred$fn__7056$fn__7057.invoke(deferred.clj:400)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__6441$f__6442.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

Note that passing other valid charset name in the value of the header, such as `utf-8` will lead to slightly different exception:

```
$ curl -gv 'localhost:5000/event' -H 'Accept-Charset: utf-8'
[snipped]
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: No implementation of method: :charset of protocol: #'yada.charset/Charset found for class: nil
        at cheshire.generate$generate.invoke(generate.clj:154)
        at cheshire.generate$generate.invoke(generate.clj:124)
        at cheshire.core$generate_string.invoke(core.clj:73)
        at yada.body$eval20657$fn__20658.invoke(body.clj:166)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at yada.body$eval20637$fn__20638.invoke(body.clj:89)
        at yada.body$eval20501$fn__20502$G__20490__20509.invoke(body.clj:34)
        at yada.handler$standard_error.invoke(handler.clj:73)
        at yada.handler$handle_request_with_maybe_subresources$fn__24625.invoke(handler.clj:150)
        at manifold.deferred$catch_SINGLEQUOTE_$fn__7283.invoke(deferred.clj:964)
        at manifold.deferred.Listener.onError(deferred.clj:220)
        at manifold.deferred.Deferred$fn__7056$fn__7057.invoke(deferred.clj:400)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__6441$f__6442.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

And yet another exception if a bogus charset value is provided:

```
$ curl -gv 'localhost:5000/event' -H 'Accept-Charset: BOGUS@' 
[snipped]
java.lang.IllegalArgumentException: No implementation of method: :charset of protocol: #'yada.charset/Charset found for class: nil
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
        at yada.charset$eval17790$fn__17813$G__17777__17818.invoke(charset.clj:31)
        at yada.representation$charset_acceptable_QMARK_.invoke(representation.clj:92)
        at clojure.core$partial$fn__4527.invoke(core.clj:2493)
        at clojure.core$map$fn__4553.invoke(core.clj:2622)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:26)
        at clojure.core.protocols$fn__6506.invoke(protocols.clj:100)
        at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6515)
        at yada.util$best.invoke(util.clj:89)
        at yada.util$best.invoke(util.clj:87)
        at yada.representation$highest_charset_quality$fn__17995.invoke(representation.clj:119)
        at yada.representation$wrap_quality_assessor$fn__17972.invoke(representation.clj:33)
        at yada.representation$skip_rejected$fn__17969.invoke(representation.clj:26)
        at clojure.core$comp$fn__4495.invoke(core.clj:2438)
        at clojure.core$comp$fn__4495.invoke(core.clj:2438)
        at clojure.core$map$fn__4553.invoke(core.clj:2622)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$filter$fn__4580.invoke(core.clj:2679)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
        at clojure.core.protocols$fn__6506.invoke(protocols.clj:101)
        at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6519)
        at yada.util$best_by.invoke(util.clj:106)
        at yada.util$best_by.invoke(util.clj:103)
        at yada.representation$select_best_representation.invoke(representation.clj:306)
        at yada.representation$select_best_representation.invoke(representation.clj:300)
        at yada.handler$handle_request_with_maybe_subresources$fn__24625.invoke(handler.clj:130)
        at manifold.deferred$catch_SINGLEQUOTE_$fn__7283.invoke(deferred.clj:964)
        at manifold.deferred.Listener.onError(deferred.clj:220)
        at manifold.deferred.Deferred$fn__7056$fn__7057.invoke(deferred.clj:400)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__6441$f__6442.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

Reproduced on `yada` versions `1.1.35` and `1.1.37`.

**Comment by mishok13** [comment]
Now, I've spent almost half a day trying to figure out what is going on and still not sure what it is, however my hunch is that it's directly related to the way `:consumes` in resource cooperates with `yada.representation/select-best-representation`. As I couldn't figure out the exact problem we've had to resolve to simply adding an interceptor that drops `Accept-Charset` header from request but I'd prefer to avoid doing this for obvious reasons.

**Comment by mishok13** [comment]
Maybe related -- the resource is "swaggerized" with `yada/swaggered`.

**Comment by malcolmsparks** [comment]
Background context is that when there is an error, yada renegotiates the charset. Say your client can parse UTF-8 and Shift_JIS, but your resource can only produce Shift_JIS, but there's any error - do you want that error to be returned in  Shift_JIS or UTF-8? I assume you'd want it in UTF-8, especially if there's an English error message. That's why yada renegotiates. Because the error, in this case, is actually a yada internal error, it's going a bit crazy. I think the best thing for me to do is to fix the original error in this case. We still have this issue where yada should distinguish between application and its own internal errors, but that's something I'm mulling over how to do
