### ISSUE TITLE
Handle Hiccup RawString

### ISSUE THREAD

**Issue by danielcompton** [juxt/yada#165]
When upgrading to hiccup `2.0.0-alpha1`, `hiccup2.core/html` returns a RawString where previously it returned a String (I think?). This caused an error in Aleph: 

```
17:14:25.854 [aleph-netty-server-event-pool-12-2] ERROR aleph.http.core - error sending body of type  hiccup.util.RawString
java.lang.IllegalArgumentException: Don't know how to convert class hiccup.util.RawString into (stream-of io.netty.buffer.ByteBuf)
        at byte_streams$convert.invokeStatic(byte_streams.clj:196)
        at byte_streams$convert.invoke(byte_streams.clj:162)
        at aleph.netty$to_byte_buf_stream.invokeStatic(netty.clj:171)
        at aleph.netty$to_byte_buf_stream.invoke(netty.clj:170)
        at aleph.http.core$send_streaming_body.invokeStatic(core.clj:287)
```

If we do we want to handle this, what is the right protocol to coerce to? At first I thought ResourceCoercion, but I don't think that's right. Or should this be handled by the Aleph layer below?

**Comment by malcolmsparks** [comment]
The protocol concerned is `yada.body.MessageBody`:

**Comment by SevereOverfl0w** [comment]
Worth noting that this only affects you if you use the new functions, the old ones still work just fine. (No breakage, just growth!)

**Comment by malcolmsparks** [comment]
@danielcompton for now, extend the `yada.body.MessageBody` protocol (see `src/yada/body.clj` for examples)

Currently yada (core) depends on hiccup 1.x - only for creating nicer error reports. I did consider putting hiccup in an extension (`ext/hiccup`) but decided against it. But there's an argument that `yada/lean` does not need hiccup and `yada/default` could/should upgrade to hiccup 2.x.

Let's keep this issue open for now.

**Comment by SevereOverfl0w** [comment]
hiccup 2.x is completely backwards compatible afaik.

**Comment by danielcompton** [comment]
Neat thanks. Here's what I did for reference, or other searchers:

```
(extend-protocol MessageBody
  RawString
  (to-body [rs representation]
    (to-body (str rs) representation))
  (content-length [rs]
    nil))
```
