### ISSUE TITLE
`unset-cookie` broken

### ISSUE THREAD

**Issue by SevereOverfl0w** [juxt/yada#263]
when unsetting the cookie, the cookie :expires is validated against `s/Inst`, but `unset-cookie` sets `:expires` to 0 which is not an inst, causing a :boom:.

```
clojure.lang.ExceptionInfo: Value does not match schema: {:expires (not (matches-some-precondition? 0))}
        at schema.core$validator$fn__20335.invoke(core.clj:155)
        at schema.core$validate.invokeStatic(core.clj:164)
        at schema.core$validate.invoke(core.clj:159)
        at yada.cookies$unset_cookie.invokeStatic(cookies.clj:134)
        at yada.cookies$unset_cookie.invoke(cookies.clj:119)
        at myproj.http.account$eval68908$fn__68910$fn__68912.invoke(account.clj:85)
        at yada.methods$apply_response_fn.invokeStatic(methods.clj:31)
        at yada.methods$apply_response_fn.invoke(methods.clj:30)
        at yada.methods$eval41964$fn__41971.invoke(methods.clj:296)
        at yada.methods$eval41618$fn__41641$G__41609__41648.invoke(methods.clj:49)
        at yada.interceptors$invoke_method.invokeStatic(interceptors.clj:311)
        at yada.interceptors$invoke_method.invoke(interceptors.clj:301)
        at manifold.deferred$eval26655$chain___26676.invoke(deferred.clj:862)
        at manifold.deferred$eval26655$chain___26676.doInvoke(deferred.clj:883)
        at clojure.lang.RestFn.applyTo(RestFn.java:151)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:660)
        at manifold.deferred$eval26655$chain___26676$fn__26680.invoke(deferred.clj:888)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__26454.invoke(deferred.clj:381)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__25833$f__25834.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)
17:54:27.264 ERROR yada.handler [manifold-pool-52-1]
ex-data: {:type :schema.core/error, :schema {:value (pred yada.cookies/fn--43337), #schema.core.OptionalKey{:k :expires} (cond-pre Inst (pred yada.cookies/fn--43339) (pred yada.cookies/fn--43331)), #schema.core.OptionalKey{:k :max-age} (cond-pre Str Int), #schema.core.OptionalKey{:k :domain} (pred "domain"), #schema.core.OptionalKey{:k :path} (pred yada.cookies/fn--43343), #schema.core.OptionalKey{:k :secure} java.lang.Boolean, #schema.core.OptionalKey{:k :http-only} java.lang.Boolean, (constrained Keyword namespace) Any}, :value {:value "", :expires 0}, :error {:expires (not (matches-some-precondition? 0))}}
```

**Comment by SevereOverfl0w** [comment]
I'm struggling to work around this due to other bugs:

- The schema disallows strings for :expire, even though later in the pipeline yada allows them
- `(java.util.Date. 0)` causes a new error:

```
java.lang.ClassCastException: class java.util.Date cannot be cast to class org.joda.time.ReadableInstant (java.util.Date is in module java.base of loader 'bootstrap'; org.joda.time.ReadableInstant is in unnamed module of loader 'app')
        at clj_time.format$unparse.invokeStatic(format.clj:200)
        at clj_time.format$unparse.invoke(format.clj:200)
        at yada.cookies$encode_attributes$iter__43347__43351$fn__43352$fn__43353.invoke(cookies.clj:52)
        at yada.cookies$encode_attributes$iter__43347__43351$fn__43352.invoke(cookies.clj:44)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:531)
        at clojure.core$seq__5387.invokeStatic(core.clj:137)
        at clojure.core$apply.invokeStatic(core.clj:660)
        at clojure.core$apply.invoke(core.clj:660)
        at yada.cookies$encode_attributes.invokeStatic(cookies.clj:43)
        at yada.cookies$encode_attributes.invoke(cookies.clj:42)
        at yada.cookies$encode_cookie.invokeStatic(cookies.clj:61)
        at yada.cookies$encode_cookie.invoke(cookies.clj:59)
        at clojure.core$map$fn__5851.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:531)
        at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38)
        at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:323)
        at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:135)
        at aleph.http.core$map__GT_headers_BANG_.invokeStatic(core.clj:141)
        at aleph.http.core$map__GT_headers_BANG_.invoke(core.clj:131)
        at aleph.http.core$ring_response__GT_netty_response.invokeStatic(core.clj:154)
        at aleph.http.core$ring_response__GT_netty_response.invoke(core.clj:146)
        at aleph.http.server$eval39890$send_response__39895$fn__39899.invoke(server.clj:113)
        at aleph.http.server$eval39890$send_response__39895.invoke(server.clj:112)
        at aleph.http.server$handle_request$fn__39927$fn__39928.invoke(server.clj:185)
        at manifold.deferred$eval26612$chain_SINGLEQUOTE____26633.invoke(deferred.clj:749)
        at manifold.deferred$eval26612$subscribe__26613$fn__26618.invoke(deferred.clj:715)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__26458.invoke(deferred.clj:398)
        at manifold.deferred.Deferred.success(deferred.clj:398)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
        at manifold.deferred$catch_SINGLEQUOTE_$fn__26704.invoke(deferred.clj:959)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__26458.invoke(deferred.clj:398)
        at manifold.deferred.Deferred.success(deferred.clj:398)
        at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
        at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
        at manifold.deferred$eval26612$chain_SINGLEQUOTE____26633.invoke(deferred.clj:736)
        at manifold.deferred$eval26612$subscribe__26613$fn__26614.invoke(deferred.clj:709)
        at manifold.deferred.Listener.onSuccess(deferred.clj:219)
        at manifold.deferred.Deferred$fn__26458$fn__26459.invoke(deferred.clj:398)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
        at manifold.executor$thread_factory$reify__25833$f__25834.invoke(executor.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
