### ISSUE TITLE
cannot treat nil as http response

### ISSUE THREAD

**Issue by rhacker** [juxt/yada#48]
I have this error when trying out yada and aleph

```
(ns components.yada
  (:require
   [clojure.pprint :refer [pprint]]
   [bidi.ring :refer [make-handler] :as bidi]
   [yada.yada :refer [yada] :as yada]
   [aleph.http :refer [start-server]]))

(def api
  ["/" {"hello" (yada "hello world" {:id :hello})
        "hello-atom" (yada (atom "hello world"))}])

(def server
  (start-server
   (bidi/make-handler api)
   {:port 3000}))
#_(.close server)
```

when I visit `http://localhost:3000/
```
java.lang.IllegalArgumentException: cannot treat nil as HTTP response for request to ''
	at aleph.http.server$invalid_value_response.invoke(server.clj:131)
	at aleph.http.server$handle_request$fn__23992$fn__23993.invoke(server.clj:184)
	at manifold.deferred$eval5912$chain_SINGLEQUOTE____5933.invoke(deferred.clj:750)
	at manifold.deferred$eval5912$subscribe__5913$fn__5918.invoke(deferred.clj:716)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__5755.invoke(deferred.clj:396)
	at manifold.deferred.Deferred.success(deferred.clj:396)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:243)
	at manifold.deferred$catch_SINGLEQUOTE_$fn__5996.invoke(deferred.clj:959)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__5755.invoke(deferred.clj:396)
	at manifold.deferred.Deferred.success(deferred.clj:396)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:243)
	at manifold.deferred$eval5912$chain_SINGLEQUOTE____5933.invoke(deferred.clj:737)
	at manifold.deferred$eval5912$subscribe__5913$fn__5914.invoke(deferred.clj:710)
	at manifold.deferred.Listener.onSuccess(deferred.clj:219)
	at manifold.deferred.Deferred$fn__5755.invoke(deferred.clj:396)
	at manifold.deferred.Deferred.success(deferred.clj:396)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:243)
	at aleph.http.server$handle_request$fn__23977$f__5358__auto____23978.invoke(server.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__5240$f__5241.invoke(executor.clj:36)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

I'm very new to yada, so I'm sure I might miss something, but according to the manual this should work.

**Comment by malcolmsparks** [comment]
Try `http://localhost:3000/hello` or `http://localhost:3000/hello-atom`

The reason is fails is that there is no route for `/` and there is no handler defined for the case where no route matches. IIRC you can actually do this in bidi by providing a catch-all `true` - but make sure you use the 'vector-of-vectors' form rather than the map, because it's important the `true` is matched last.

```clojure
["/" [["hello" (yada "hello world" {:id :hello})]
       ["hello-atom" (yada (atom "hello world"))]
       [true (yada nil)]]]
```

**Comment by rhacker** [comment]
thanks !
